version: "3"

services:
  techtalks.producer:
    image: ngacrregistry.azurecr.io/nileshgule/techtalksproducer:rabbitmq-keda-7.0
    build:
      context: src
      dockerfile: Dockerfile-TechTalksMQProducer

  techtalks.consumer:
    image: ngacrregistry.azurecr.io/nileshgule/techtalksconsumer:rabbitmq-keda-7.0
    build:
      context: src
      # dockerfile: Dockerfile-TechTalksMQConsumer
      dockerfile: Dockerfile-TechTalksMQConsumer-7.0
